Repository UTSAVS26/PySnippets, pull requests merged in 2024-11, with the labels that each got.

#297 ✅ Add Caesar-cipher algorithm
  Tests/Cipher_algorithms/test_caesar_cipher.py
  pysnippets/Cipher_algorithms/caesar_cipher.py
Labels: Contributor, level1, gssoc-ext

#301 Create SECURITY.md
  SECURITY.md
Labels: Contributor, level1, gssoc-ext

#310 ✅ Add Vigenère cipher implementation and unit tests
  Tests/Cipher_algorithms/test_Vigenère_Cipher.py
  pysnippets/Cipher_algorithms/Vigenère_Cipher.py
Labels: Contributor, level1, gssoc-ext

#314 Refactor and Enhance Classical Ciphers: `Rail Fence`, `Playfair`, `Caesar`, `Affine`, and `Vigenère`
  pysnippets/Cipher_algorithms/Rail_Fence_Cipher.py
  pysnippets/Cipher_algorithms/Vigenère_Cipher.py
  pysnippets/Cipher_algorithms/affine_cipher.py
  pysnippets/Cipher_algorithms/caesar_cipher.py
  pysnippets/Cipher_algorithms/playfair_cipher.py
Labels: Contributor, level2, gssoc-ext

#312 ✅ Add Hill cipher implementation and unit tests
  .github/workflows/auto-label.yml
  Tests/Cipher_algorithms/test_hill_cipher.py
  pysnippets/Cipher_algorithms/hill_cipher.py
Labels: Contributor, level1, gssoc-ext

#335 ✨ Enhance the Communications code snippets
  Tests/Communication/test_send_email.py
  pysnippets/Communication/communication.md
  pysnippets/Communication/send_email.py
  pysnippets/Communication/test_send_email.py
Labels: Contributor, level3, gssoc-ext

#336 fix: 🐛 Add new features to utilize less space & lengthy call
  pysnippets/Cipher_algorithms/__init__.py
  pysnippets/Cipher_algorithms/affine_cipher.py
  pysnippets/Cipher_algorithms/cipher_manager.py
  pysnippets/Cipher_algorithms/test_cipher_manager.py
Labels: Contributor, level2, gssoc-ext

#337 fix: 🐛 Optimize the code for better call, and less time utilize
  pysnippets/Image_Processing/__init__.py
  pysnippets/Image_Processing/image_processing.py
  pysnippets/Image_Processing/test_image_processing.py
  pysnippets/Memoisation/__init__.py
  pysnippets/Memoisation/fibonacci.py
  pysnippets/Memoisation/knapsack.py
  pysnippets/Memoisation/lcs.py
  pysnippets/Memoisation/test_memoization.py
Labels: Contributor, level3, gssoc-ext

#338 ✅ Optimized the Numbers & PDF Manipulation code snippets
  Tests/Cipher_algorithms/test_Rail_Fence_Cipher.py
  Tests/Cipher_algorithms/test_Vigenère_Cipher.py
  Tests/Cipher_algorithms/test_affine_cipher.py
  Tests/Cipher_algorithms/test_caesar_cipher.py
  Tests/Cipher_algorithms/test_hill_cipher.py
  Tests/Cipher_algorithms/test_playfair_cipher.py
  Tests/PDF_Manipulation/test_pdf_utils.py
  Tests/image_processing/__intit.py
  Tests/image_processing/test_image.webp
  Tests/image_processing/test_image_augmentation.py
  Tests/numbers/test_format_to_2_decimal.py
  Tests/numbers/test_number_formatting.py
  Tests/numbers/test_pad_with_zeros.py
  Tests/numbers/test_percentage_format.py
  Tests/numbers/test_prime_factorization.py
  pysnippets/Numbers/number_formatting.py
  pysnippets/Numbers/prime_factorization.py
  pysnippets/Numbers/test_numbers.py
  pysnippets/PDF_Manipulation/pdf_reader.py
  pysnippets/PDF_Manipulation/pdf_splitter.py
  pysnippets/PDF_Manipulation/test_pdf_manipulation.py
Labels: Contributor, level3, gssoc-ext

#339 chore: 🤖 Update & refractor logic of the python snippets
  pysnippets/Dynamic Programming/coin_change.py
  pysnippets/Dynamic Programming/edit_distance.py
  pysnippets/Dynamic Programming/longest_common_subsequence.py
  pysnippets/Dynamic Programming/unique_paths.py
Labels: Contributor, level2, gssoc-ext

#372 Refactor and Enhance`LinkedList` Implementations and Tests.
  pysnippets/LinkedList/Circular_Linked_List.py
  pysnippets/LinkedList/Doubly_Linked_List.py
  pysnippets/LinkedList/Singly_Linked_List.py
  pysnippets/LinkedList/test_linked_lists.py
Labels: Contributor, level2, gssoc-ext

#375 fix: 🐛 Enhance & update the Searching code snippets
  Tests/Sorting/test_bubble_sort.py
  Tests/Sorting/test_cocktail_shaker_sort.py
  Tests/Sorting/test_cocktail_sort.py
  Tests/Sorting/test_insertion_sort.py
  Tests/Sorting/test_merge_sort.py
  Tests/Sorting/test_quick_sort.py
  Tests/Sorting/test_sort_dict_list.py
  pysnippets/Sorting/__init__.py
  pysnippets/Sorting/bubble_sort.py
  pysnippets/Sorting/cocktail_shaker_sort.py
  pysnippets/Sorting/cocktail_sort.py
  pysnippets/Sorting/counting_sort.py
  pysnippets/Sorting/heap_sort.py
  pysnippets/Sorting/insertion_sort.py
  pysnippets/Sorting/merge_sort.py
  pysnippets/Sorting/quick_sort.py
  pysnippets/Sorting/sort_dict_list.py
  pysnippets/Sorting/sorting.md
  pysnippets/models/CV_means.py
  pysnippets/models/Ensemble.py
  pysnippets/models/Grid_search.py
  pysnippets/models/KMeans.py
  pysnippets/models/LightGBM.py
  pysnippets/models/Linear_regression.py
  pysnippets/models/Logistic_regression.py
  pysnippets/models/XGB.py
Labels: Contributor, level3, gssoc-ext

#425 ✨ Refactor Search Algorithms and Add Test Cases for Edge Cases and Performance
  pysnippets/Searching/Exponential_search.py
  pysnippets/Searching/Fibonacci_search.py
  pysnippets/Searching/Interpolation.py
  pysnippets/Searching/Jump_search.py
  pysnippets/Searching/Linear_Search.py
  pysnippets/Searching/Ternary_search.py
  pysnippets/Searching/iterative_binary_search.py
  pysnippets/Searching/recursive_binary_search.py
  pysnippets/Searching/test_searching.py
Labels: Contributor, level2, gssoc-ext

#429 ✨ Updates and Enhancements to Statistical Functions
  pysnippets/stats/coeffecient_variation.py
  pysnippets/stats/correlation.py
  pysnippets/stats/iqr.py
  pysnippets/stats/kurtosis.py
  pysnippets/stats/mean_median_mode.py
  pysnippets/stats/quantile.py
  pysnippets/stats/skewness.py
  pysnippets/stats/standard_deviation.py
  pysnippets/stats/variance.py
  pysnippets/stats/z_score_normalization.py
Labels: Contributor, level2, gssoc-ext

#430 feat: 🎸 Enhance + update the Bitwise modified code snippets
  pysnippets/Bitwise/Bitwise.md
  pysnippets/Bitwise/__init__.py
  pysnippets/Bitwise/clear_lsb_upto_n.py
  pysnippets/Bitwise/count_bits.py
  pysnippets/Bitwise/find_unique.py
  pysnippets/Bitwise/flip_bit.py
  pysnippets/Bitwise/isolate_right_one.py
  pysnippets/Bitwise/power.py
  pysnippets/Bitwise/swap.py
  pysnippets/Bitwise/test_all.py
Labels: Contributor, level2, gssoc-ext
