Repository UTSAVS26/PySnippets, pull requests merged in 2024-10, with the labels that each got.

#11 Addition of File organizer snippet
  Tests/test_file_organizer.py
  pysnippets/File_Organizer/__init__.py
  pysnippets/File_Organizer/file_organizer.py
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted, Contributor, Level1, gssoc-ext

#57 Added Binary search Algorithm snippet Feature
  Tests/algorithms/test_binary_search.py
  pysnippets/algorithms/binary_search.py
Labels: hacktoberfest, hacktoberfest-accepted, Contributor, Level1, gssoc-ext

#56 Enhance the string_manipulation file by adding methods to improve string handling capabilities.| Issue #36
  Tests/strings/test_string_manipulation_added.py
  pysnippets/Strings/string_manipulation.py
Labels: hacktoberfest, hacktoberfest-accepted, Contributor, Level1, gssoc-ext

#58 Pull Request For Issues #46 #49
  Structure.md
  Tests/analysis/test_analysis.py
  pysnippets/Files/files.md
  pysnippets/analysis/DataUtils.py
  pysnippets/analysis/ModelUtils.py
  pysnippets/analysis/__init__.py
  pysnippets/analysis/datautils.md
  pysnippets/analysis/modelutils.md
  pysnippets/maths/__init__.py
  pysnippets/maths/determinant.py
  pysnippets/maths/maths.md
  pysnippets/maths/matrix_operations.py
  pysnippets/stats/stats.md
Labels: hacktoberfest, hacktoberfest-accepted, Contributor, gssoc-ext

#63 Added: Utilites package
  Tests/utilities/test_flatten.py
  Tests/utilities/test_retry.py
  Tests/utilities/test_time_execution.py
  pysnippets/utilities/__init__.py
  pysnippets/utilities/flatten.py
  pysnippets/utilities/retry.py
  pysnippets/utilities/timer.py
  pysnippets/utilities/utilities.md
Labels: hacktoberfest, hacktoberfest-accepted, Contributor, level1, gssoc-ext

#76 Added Prime Factorization Function to Numbers Category and number import error resolved
  Tests/numbers/test_number_formatting.py
  Tests/numbers/test_prime_factorization.py
  pysnippets/Numbers/prime_factorization.py
Labels: hacktoberfest, hacktoberfest-accepted, Contributor, level2, gssoc-ext

#73 Qrcodes
  Tests/Web/test_get_image.py
  Tests/qrcode/test_generate_qr_code.py
  Tests/qrcode/test_scan_qr_code.py
  pysnippets/Web/get_image.py
  pysnippets/qrcode/__init__.py
  pysnippets/qrcode/generate_qr_code.py
  pysnippets/qrcode/scan_qr_code.py
Labels: hacktoberfest, hacktoberfest-accepted, Contributor, level2, gssoc-ext

#81 Added list manipulation methods
  Tests/lists/test_list_manipulation.py
  pysnippets/Lists/__init__.py
  pysnippets/Lists/list_manipulation.md
  pysnippets/Lists/list_manipulation.py
Labels: hacktoberfest, hacktoberfest-accepted, Contributor, level1, gssoc-ext

#72 Added graphing snippets
  Tests/graphing/__init__.py
  Tests/graphing/test_advanced_graphing.py
  pysnippets/graphing_snippets/__init__.py
  pysnippets/graphing_snippets/advanced_graphing.py
  pysnippets/graphing_snippets/graphing-example.py
  pysnippets/graphing_snippets/graphing-module-readme.md
Labels: hacktoberfest, Contributor, level2, gssoc-ext

#86 Added Operations for Vectors
  Tests/maths/test_vector_operations.py
  pysnippets/maths/vector_operations.py
Labels: hacktoberfest, hacktoberfest-accepted, Contributor, level2, gssoc-ext

#99 added graph algorithms
  Tests/algorithms/test_astar.py
  Tests/algorithms/test_bellman_ford.py
  Tests/algorithms/test_bfs.py
  Tests/algorithms/test_dfs.py
  Tests/algorithms/test_dijkstras.py
  Tests/algorithms/test_floyds.py
  Tests/algorithms/test_kruskals.py
  Tests/algorithms/test_prims.py
  Tests/algorithms/test_topological_ordering.py
  Tests/algorithms/test_warshalls.py
  pysnippets/algorithms/astar.py
  pysnippets/algorithms/bellman_ford.py
  pysnippets/algorithms/bfs.py
  pysnippets/algorithms/dfs.py
  pysnippets/algorithms/dijkstras.py
  pysnippets/algorithms/floyds.py
  pysnippets/algorithms/kruskals.py
  pysnippets/algorithms/prims.py
  pysnippets/algorithms/topological_ordering.py
  pysnippets/algorithms/warshalls.py
Labels: hacktoberfest, hacktoberfest-accepted, Contributor, level2, gssoc-ext

#123 [Feature Request]: Web Scrpaing code-snippets
  Tests/webscrape/test_scrape.py
  pysnippets/webscrape/__init__.py
  pysnippets/webscrape/scraper.py
Labels: hacktoberfest, Contributor, level1, gssoc-ext

#128 Add DFS, BFS, Dijkstra's, Prim's and Fibonacci sequence algorithms.
  Tests/algorithms/test_breadth_first_search.py
  Tests/algorithms/test_depth_first_search.py
  Tests/algorithms/test_dijkstra.py
  Tests/algorithms/test_fibonacci.py
  Tests/algorithms/test_prim.py
  pysnippets/algorithms/breadth_first_search.py
  pysnippets/algorithms/depth_first_search.py
  pysnippets/algorithms/dijkstra.py
  pysnippets/algorithms/fibonacci.py
  pysnippets/algorithms/prim.py
Labels: hacktoberfest, Contributor, level1, gssoc-ext

#136 added 1 - Formatting to 2 decimal places 2 - Padding with zeros 3 - Percentage formatting
  Tests/numbers/test_format_to_2_decimal.py
  Tests/numbers/test_pad_with_zeros.py
  Tests/numbers/test_percentage_format.py
  pysnippets/Numbers/format_to_2_decimal.md
  pysnippets/Numbers/format_to_2_decimal.py
  pysnippets/Numbers/pad_with_zeros.md
  pysnippets/Numbers/pad_with_zeros.py
  pysnippets/Numbers/percentage_format.md
  pysnippets/Numbers/percentage_format.py
Labels: hacktoberfest, hacktoberfest-accepted, Contributor, level2, gssoc-ext

#137 Added the required features in Polar Rectangular Conversion file
  Tests/maths/test_conversions.py
  pysnippets/maths/polar_rectangular_conversion.py
Labels: hacktoberfest, hacktoberfest-accepted, Contributor, level1, gssoc-ext

#135 Feature: Add Utility Snippets for Enhanced Developer Efficiency | Issue #14
  Tests/Communication/test_send_email.py
  Tests/Performance/test_memoize.py
  Tests/Performance/test_timer.py
  Tests/Sorting/test_sort_dict_list.py
  pysnippets/Communication/__init__.py
  pysnippets/Communication/send_email.py
  pysnippets/Performance/__init__.py
  pysnippets/Performance/memoize.py
  pysnippets/Performance/timer.py
  pysnippets/Sorting/__init__.py
  pysnippets/Sorting/sort_dict_list.py
Labels: hacktoberfest, Contributor, level2, gssoc-ext

#156 added utility snippets
  Tests/utilities/test_caching.py
  Tests/utilities/test_deep_copy.py
  pysnippets/utilities/caching.md
  pysnippets/utilities/caching.py
  pysnippets/utilities/deep_copy.md
  pysnippets/utilities/deep_copy.py
Labels: hacktoberfest, Contributor, level1, gssoc-ext

#165 Add robust image augmentation module with tests and README
  Tests/image_processing/__intit.py
  Tests/image_processing/test_image.webp
  Tests/image_processing/test_image_augmentation.py
  pysnippets/Image_Processing/ImageAugmentation.md
  pysnippets/Image_Processing/__init__.py
  pysnippets/Image_Processing/image_augmentation_module.py
  pysnippets/Image_Processing/test_image.webp
  pysnippets/Image_Processing/usage.py
Labels: hacktoberfest, hacktoberfest-accepted, Contributor, level1, gssoc-ext

#175 [Bug]: Inconsistent Sorting Algorithms
  Tests/Sorting/test_bubble_sort.py
  Tests/Sorting/test_insertion_sort.py
  Tests/Sorting/test_merge_sort.py
  Tests/Sorting/test_quick_sort.py
  pysnippets/Sorting/__init__.py
  pysnippets/Sorting/bubble_sort.py
  pysnippets/Sorting/insertion_sort.py
  pysnippets/Sorting/merge_sort.py
  pysnippets/Sorting/quick_sort.py
  pysnippets/Sorting/sort_dict_list.py
Labels: hacktoberfest, hacktoberfest-accepted, Contributor, level2, gssoc-ext

#152 Improved README
  .github/workflows/add-contributor.yml
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, Contributor, level1, gssoc-ext

#157 Added Encryption algorithms in Algorithms
  Tests/algorithms/test_advanced_encryption_standard.py
  Tests/algorithms/test_asymmetric_encryption_algorithm.py
  Tests/algorithms/test_elliptic_curve_cryptography.py
  Tests/algorithms/test_hashing.py
  Tests/algorithms/test_symmetric_encryption_algorithm.py
  pysnippets/algorithms/Encryption algorithm/advanced_encryption_standard.py
  pysnippets/algorithms/Encryption algorithm/asymmetric_encryption_algorithm.py
  pysnippets/algorithms/Encryption algorithm/elliptic_curve_cryptography.py
  pysnippets/algorithms/Encryption algorithm/hashing.py
  pysnippets/algorithms/Encryption algorithm/symmetric_encryption_algorithm.py
Labels: hacktoberfest, Contributor, level1, gssoc-ext

#192 Modified README.md file.
  CONTRIBUTING.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, Contributor, level1, gssoc-ext

#177 Added dictionary manipulation methods
  Tests/dictionary/test_dict_manipulation.py
  pysnippets/dictionary/__init__.py
  pysnippets/dictionary/dict_manipulation.md
  pysnippets/dictionary/dict_manipulation.py
Labels: hacktoberfest, Contributor, level1, gssoc-ext

#155 added the fibonacci generator
  Tests/maths/test_fibonacci_sequence.py
  Tests/maths/test_pascals_triangle.py
  pysnippets/maths/fibonacci_sequence.py
  pysnippets/maths/pascals_triangle.py
Labels: hacktoberfest, Contributor, level1, gssoc-ext

#281 Add GitHub Workflow
  .github/workflows/auto-label.yml
  .github/workflows/detect-duplicate.yml
  DIRECTORY.md
Labels: hacktoberfest, hacktoberfest-accepted, Contributor, level1, gssoc-ext
